# config.properties

# Valori possibili: CLI, GUI
ui.type=GUI

persistence.type=DEMO
# Valori possibili: DEMO, FILESYSTEM, DATABASE


# Parametri JDBC
db.url=jdbc:mysql://localhost:3306/unifinance_db
db.user=admin_unifinance
db.pass=unifinance
db.driver=com.mysql.cj.jdbc.Driver


file.utenti=utenti.csv
file.professori=professori.csv
file.studenti=studenti.csv
file.classi=classi.csv
file.transazioni=transazioni.csv
file.wallet=wallet.csv